import = [
  "~/.rice/alacritty/dracula.toml",
  # "./catppuccin-mocha.toml"
  # "./catppuccin-macchiato.toml"
  # "./catppuccin-frappe.toml"
  # "./catppuccin-latte.toml"
  # "./tokyonight-day.toml"
  # "./tokyonight-moon.toml"
  # "./tokyonight-night.toml"
  # "./tokyonight-storm.toml"
]

[font]
size = 11

[font.bold]
family = "JetBrainsMonoNL"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMonoNL"
style = "BoldItalic"

[font.italic]
family = "JetBrainsMonoNL"
style = "MediumItalic"

[font.normal]
family = "JetBrainsMonoNL"
style = "Medium"

[font.offset]
x = 1
y = 1

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = false

[shell]
program = "/usr/bin/zsh"

[window]
opacity = 0.97
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 0
y = 0

[[keyboard.bindings]]
action = "ReceiveChar"
key = "j"
mods = "Control"
