#!/bin/sh

## Start
$HOME/.local/bin/autostart &

# Monitors
bspc monitor HDMI-0 -d 1 2 3 4 # then some workspaces goes to HDMI
bspc monitor DP-2 -d 5 6 7 8 9 0 # and some workspaces goes to DP

## General Configs
bspc config border_width         2
bspc config window_gap           10


bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true


## Rules
bspc rule -a "Alacritty"        state=floating
bspc rule -a "Android Emulator" manage=off
bspc rule -a "Emulator"         manage=off
bspc rule -a "Opera"						desktop=^7
bspc rule -a "librewolf"				desktop=^5
bspc rule -a "discord"          desktop=^6

## Border Colors
bspc config normal_border_color "#333333"
bspc config active_border_color "#333333"
bspc config focused_border_color "#d6345b"
bspc config presel_feedback_color "#333333"
bspc config urgent_border_color "#d6345b"
