#!/bin/sh

# Setup the each component

# First [autostart script]
mkdir -p $HOME/.local/bin

ln -sf $HOME/.rice/.local/bin/autostart $HOME/.local/bin/autostart
ln -sf $HOME/.rice/.local/bin/powermenu $HOME/.local/bin/powermenu
