#!/bin/sh
# Xsetup - run as root before the login dialog appears

# get the correct actual monitor names with
sleep 0.5
if [[ $(xrandr -q | grep "HDMI-0 disconnected" )]];
then
  xrandr --output DP-2 --auto
elif [[ $(xrandr -q | grep "DP-2 disconnected" )]];
  xrandr --output HDMI-0 --auto
else
  xrandr --output DP-2 --rotate normal --output HDMI-0 --rotate normal --left-of DP-2
fi
