#!/bin/sh
# Xsetup - run as root before the login dialog appears

# get the correct actual monitor names with
# xrandr | awk ' /connected/ { print $1, $2 }'
mon1=DP-2
mon2=HDMI-0

sleep .5
if xrandr | grep "$mon1 disconnected"; then
    xrandr --output "$mon2" --auto
else
    xrandr --output "$mon1" --auto
fi

